export { default as Navbar } from "./Navbar";
export { default as SimpleAccordion } from "./SimpleAccordion";
export { default as FloatingButton } from "./FloatingButton";
export { default as CoursesListWithFilters } from "./CoursesListWithFilters";
export { default as CourseContent } from "./course/CourseContent";
export { default as CourseHeader } from "./course/CourseHeader";
export { default as CoursePrice } from "./CoursePrice";
export { default as CourseReviews } from "./course/CourseReviews";
export { default as VideoPlayer } from "./VideoPlayer";
