name: CI
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # set environment variables
            - uses: actions/checkout@v2
            - name: Install modules
              run: cd server; npm install --legacy-peer-deps
            - name: Run test
              env:
                  MONGO_TEST_URL: ${{ secrets.MONGO_TEST_URL }}{{ github.run_id }}?retryWrites=true&w=majority

              run: cd server; npm test
